import Header from "./components/Header";
import "./globals.css";
import { Montserrat } from "next/font/google";
import { ThemeProvider } from "./provider/theme-provider";

const mont = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Lgdev",
  description: "Portfolio generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${mont.className}`}>
      <body className="bg-light dark:bg-dark">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
