import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";

const mont = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Portfolio",
  description: "Portfolio generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${mont.className}`}>
      <body className="bg-light scroll-smooth">
        <Header />
        <main className="pt-[72px] w-[80vw] m-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
